version: '3'
services:
  jogging:
    image: "jogging"
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/jogging
      - spring.datasource.password=123
      - weather.provider.key=my_secret_key
      - weather.checkTime=*/30 * * * * *
  mysql:
    image: "mysql:5.7"
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - "/Users/nickolay/Documents/hobby/mysql:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=123