spring:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://localhost:3306/jogging
    username: jogging
    password: 123

weather:
  checkTime: '*/10 * * * * *' #Every 10 seconds
  provider:
    url: http://api.apixu.com/v1
    key: my_secret_key